### ISSUE TITLE
Go-live Finishing Touches

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint.org#117]
Before we can go live with this site, we need to complete the following steps:

- [x] eslint/eslint.org#134
- [x] eslint/eslint.org#136
- [x] eslint/eslint.org#124
- [x] eslint/eslint.org#118
- [x] eslint/eslint.org#138
- [x] eslint/eslint.org#139
- [x] https://github.com/eslint/new.eslint.org/issues/231
- [x] https://github.com/eslint/new.eslint.org/issues/232
- [x] https://github.com/eslint/new.eslint.org/issues/233
- [x] https://github.com/eslint/eslint/pull/16007
- [x] https://github.com/eslint/eslint/issues/15948
- [x] https://github.com/eslint/eslint/issues/15997
- [x] https://github.com/eslint/eslint/issues/15844
- [x] https://github.com/eslint/eslint/issues/16008
- [x] https://github.com/eslint/eslint/issues/16009
- [x] https://github.com/eslint/eslint/issues/16010
- [x] https://github.com/eslint/eslint/issues/16011
- [x] https://github.com/eslint/eslint/issues/16012
- [x] https://github.com/eslint/eslint/issues/15977
- [x] https://github.com/eslint/eslint/issues/16013
- [x] eslint/eslint#16051

**Comment by mdjermanovic** [comment]
I updated the list with the remaining issues that I am aware of.

**Comment by nzakas** [comment]
All of the tasks in the checklist are closed, so closing.
